[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[client]
showErrorDetails = false
maxUploadSize = 500

[server]
port = 8501
headless = true
runOnSave = true
maxUploadSize = 500

[logger]
level = "info"
